### ISSUE TITLE
Prevent SIOOBE when JDK build is archived

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#170]
The following exception was raised when JDK 14 was no longer "GA", i.e. the page at https://jdk.java.net/14 doesn't contain a valid link anymore.
```
src/bach/ShowJdkBuilds.java > install-jdk.properties

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 38, end -1, length 2806
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at ShowJdkBuilds.substring(ShowJdkBuilds.java:103)
	at ShowJdkBuilds.parse(ShowJdkBuilds.java:55)
	at ShowJdkBuilds.main(ShowJdkBuilds.java:37)

```

Work-around applied via https://github.com/sormuras/bach/commit/4a3dab375937f7be6e839da39b81f4f91d218360

**Comment by sormuras** [comment]
Fixed via https://github.com/sormuras/bach/commit/c34f8e212e7ee76ee3fba9aa0df19cde30c46516
