### ISSUE TITLE
Module `jdk.xml.dom` not found at test runtime

### ISSUE THREAD

**Issue by sormuras** [sormuras/bach#217]
Having module `jdk.xml.dom` and module `jdk.zipfs` in a test module, like:

```java
open /*test*/ module test.base {
  exports test.base;

  requires transitive org.junit.jupiter;
  requires jdk.xml.dom;
  requires jdk.zipfs;

  provides java.util.spi.ToolProvider with
      test.base.TestProvider1,
      test.base.TestProvider2;
}
```

...and `javac` compiling them (this and other test modules) like a charm:

```shell
javac  --module com.github.sormuras.bach,test.base,test.integration,test.projects --module-source-path .\*\te[...]
```

...yields this error at test runtime:

```
java.lang.module.FindException: Module jdk.xml.dom not found, required by test.base
        at java.base/java.lang.module.Resolver.findFail(Resolver.java:900)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:492)
        at com.github.sormuras.bach@17+BOOTSTRAP+2021-03-24T19:40:11.030592800Z/com.github.sormuras.bach.internal.ModuleLayerBuilder.build(ModuleLayerBuilder.java:115)
        at com.github.sormuras.bach@17+BOOTSTRAP+2021-03-24T19:40:11.030592800Z/com.github.sormuras.bach.api.ToolProviderAPI.computeToolProviders(ToolProviderAPI.java:27)
        at com.github.sormuras.bach@17+BOOTSTRAP+2021-03-24T19:40:11.030592800Z/com.github.sormuras.bach.api.ProjectBuildTestSpaceAPI.buildProjectTestRuns(ProjectBuildTestSpaceAPI.java:106)
        at com.github.sormuras.bach@17+BOOTSTRAP+2021-03-24T19:40:11.030592800Z/com.github.sormuras.bach.api.ProjectBuildTestSpaceAPI.buildProjectTestSpace(ProjectBuildTestSpaceAPI.java:50)
[...]
```

Aren't all system modules added to the module graph by default?

**Comment by sormuras** [comment]
`java --help` says:
```
    --add-modules <module name>[,<module name>...]
                  root modules to resolve in addition to the initial module.
                  <module name> can also be ALL-DEFAULT, ALL-SYSTEM,
                  ALL-MODULE-PATH.
```

Adding `--add-modules ALL-DEFAULT` or `--add-modules ALL-SYSTEM` to the command that launches module `com.github.sormuras.bach`:

https://github.com/sormuras/bach/blob/0168338c7ab99b48bcd7fc8ae3c75fdd1f61e438/.bach/bin/bach.bat#L18

...helps -- but introduces "other issues" around here:

https://github.com/sormuras/bach/blob/0168338c7ab99b48bcd7fc8ae3c75fdd1f61e438/com.github.sormuras.bach/main/java/com/github/sormuras/bach/api/ProjectBuildTestSpaceAPI.java#L103

**Comment by sormuras** [comment]
The "other issues" were due to a dirty workspace.
