### ISSUE TITLE
Bach init 17ea will deletes the local Bach jar

### ISSUE THREAD

**Issue by carldea** [sormuras/bach#225]
I’m not sure if this is a bug or not. 
When i do the following:
```bash
$ bach init 17ea
```
Notice above I forgot the hyphen. It sh/b 17-ea. When I hit enter it will try and find jar on github getting a 404 error. Bach will deletes the local jar. Should it do that? 
As a user(panicky), I’d do a `bach clean` and get module not found… (b/c it’s deleted).

```bash
cdea-MBP:worldclock cdea$ bach init 17ea

    528 .bach/bin/bach
    537 .bach/bin/bach.bat
 26,289 .bach/bin/boot.java
    563 .bach/bin/boot.jsh
  2,926 .bach/bin/init.java
Exception in thread "main" java.io.FileNotFoundException: https://github.com/sormuras/bach/releases/download/17ea/com.github.sormuras.bach@17ea.jar
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1981)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at java.base/java.net.URL.openStream(URL.java:1167)
        at init.copy(init.java:84)
        at init.loadModule(init.java:79)
        at init.main(init.java:30)
```

To fix the problem I basically did the following:
```bash
bach init 17-ea
```

**Comment by sormuras** [comment]
It's a rough edge of `init.java` - it should check user's input before starting the initialization process.

At least: test whether `https://github.com/sormuras/bach/releases/download/$VERSION/com.github.sormuras.bach@$VERSION.jar` is available via a HEAD request.
Or: pre-download all assets into a temporary directoy and only overwrite existing files on success

Neat: `bach init` could list available versions OR enter an interactive mode where it presents available versions and waits for user's selection.

**Comment by carldea** [comment]
Agreed.

Suggestions:
If Bach will use the Disco Api in the future could it be `bach list java`?

`bach list`
Bach list is just showing Bach’s latest. Just throwing ideas your way if you want the command Line to be concise. And the interactive portion just to be on jshell. 
Eitherway 😃👍🏻

Thanks!!!
